export const artists = [
    {
        "id": 0,
        "name": "Michael Jackson",
        "Gender": "Male",
        "birthdate": "August 29, 1958",
        "activeSince": "1964",
        "genres": ["Pop", "R&B"],
        "labels": ["Epic Records"],
        "website": "https://www.michaeljackson.com/",
        "image": "https://upload.wikimedia.org/wikipedia/commons/5/5b/Michael_Jackson_in_1988_%28enhanced%29.jpg",
        "shortDescription": "King of Pop known for his iconic music and performances."
    },
    {
        "id": 1,
        "name": "The Beatles",
        "Gender": "Male",
        "birthdate": "Formed in 1960",
        "activeSince": "1960s",
        "genres": ["Rock", "Pop"],
        "labels": ["Apple Records"],
        "website": "https://www.thebeatles.com/",
        "image": "https://upload.wikimedia.org/wikipedia/commons/b/bd/The_Beatles_with_Jimmie_Nicol_916-5098.jpg",
        "shortDescription": "Legendary British rock band that revolutionized music."
    },
    {
        "id": 2,
        "name": "Bob Marley",
        "Gender": "Male",
        "birthdate": "February 6, 1945",
        "activeSince": "1962",
        "genres": ["Reggae"],
        "labels": ["Tuff Gong"],
        "website": "https://www.bobmarley.com/",
        "image": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Bob_Marley_in_1980.jpg",
        "shortDescription": "Reggae icon and global ambassador for peace."
    },
    {
        "id": 3,
        "name": "Elvis Presley",
        "Gender": "Male",
        "birthdate": "January 8, 1935",
        "activeSince": "1954",
        "genres": ["Rock and Roll"],
        "labels": ["RCA Records"],
        "website": "https://www.elvis.com/",
        "image": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Elvis_Presley.jpg",
        "shortDescription": "The King of Rock and Roll, known for his charisma and music."
    },
    {
        "id": 4,
        "name": "Beyoncé",
        "Gender": "Female",
        "birthdate": "September 4, 1981",
        "activeSince": "Late 1990s",
        "genres": ["R&B", "Pop"],
        "labels": ["Columbia Records"],
        "website": "https://www.beyonce.com/",
        "image": "https://upload.wikimedia.org/wikipedia/commons/9/9e/Beyonce-2008_2.jpg",
        "shortDescription": "Global superstar and powerful vocalist."
    },
    {
        "id": 5,
        "name": "Miles Davis",
        "Gender": "Male",
        "birthdate": "May 26, 1926",
        "activeSince": "1940s",
        "genres": ["Jazz"],
        "labels": ["Columbia Records"],
        "website": "https://www.milesdavis.com/",
        "image": "https://upload.wikimedia.org/wikipedia/commons/2/24/Miles_Davis_by_Palumbo_cropped.jpg",
        "shortDescription": "Influential jazz trumpeter and composer."
    },
    {
        "id": 6,
        "name": "Madonna",
        "Gender": "Female",
        "birthdate": "August 16, 1958",
        "activeSince": "1980s",
        "genres": ["Pop", "Dance"],
        "labels": ["Sire Records"],
        "website": "https://www.madonna.com/",
        "image": "https://live.staticflickr.com/6126/5999574175_a79793bcea_c.jpg",
        "shortDescription": "Queen of Pop and cultural icon."
    },
    {
        "id": 7,
        "name": "Prince",
        "Gender": "Male",
        "birthdate": "June 7, 1958",
        "activeSince": "Late 1970s",
        "genres": ["Pop", "Funk", "R&B"],
        "labels": ["Warner Bros. Records"],
        "website": "https://prince.com/",
        "image": "https://upload.wikimedia.org/wikipedia/commons/3/34/Prince_%28cropped%29.jpg",
        "shortDescription": "Musical genius and iconic performer."
    },
    {
        "id": 8,
        "name": "Adele",
        "Gender": "Female",
        "birthdate": "May 5, 1988",
        "activeSince": "2000s",
        "genres": ["Pop", "Soul"],
        "labels": ["XL Recordings"],
        "website": "https://www.adele.com/",
        "image": "https://upload.wikimedia.org/wikipedia/commons/e/e4/Adele_-_Live_2009_%284%29.jpg",
        "shortDescription": "Soulful British singer-songwriter with a powerful voice."
    },
    {
        "id": 9,
        "name": "David Bowie",
        "Gender": "Male",
        "birthdate": "January 8, 1947",
        "activeSince": "1960s",
        "genres": ["Rock", "Pop"],
        "labels": ["RCA Records"],
        "website": "https://www.davidbowie.com/",
        "image": "https://upload.wikimedia.org/wikipedia/commons/0/0c/David_Bowie_-_TopPop_1974_03_%28cropped%29.png",
        "shortDescription": "Music chameleon and influential rock artist."
    }
]